export const homeContent = {
  fa: {
    title: "بازار را بشناسید، کسب‌وکار را مدیریت کنید", eyebrow: "بازار کاویان | فولاد و ضایعات",
    description: "بازار کاویان؛ معرفی فرصت‌های فولاد و ضایعات، نرخ‌ها و تحلیل بازار، همراه با ERP متناسب با فرایند کسب‌وکار.",
    heroText: "فرصت‌های مزایده، نرخ‌ها و چشم‌انداز بازار را دنبال کنید و با ERP متناسب با فرایندهای کسب‌وکار خود آشنا شوید.",
    marketLink: "ورود به بازار کاویان", erpLink: "معرفی ERP", quote: "استعلام قیمت", productsLink: "مشاهده محصولات", explore: "آشنایی با حوزه‌های فعالیت",
    sectorLabel: "حوزه‌های فعالیت", sectorTitle: "از محصول فولادی تا چرخه‌ی بازیافت",
    sectorText: "مسیرهای اصلی فعالیت هلدینگ را بشناسید و متناسب با نیاز خود، ادامه دهید.",
    sectors: [
      { title: "محصولات فولادی", text: "آهن‌آلات و محصولات فولادی برای نیازهای صنعتی، ساختمانی و پروژه‌ای.", path: "/products", link: "محصولات" },
      { title: "ضایعات صنعتی", text: "آشنایی با ضایعات فلزی و مسیر خرید و فروش در چرخه‌ی تأمین صنعت.", path: "/scrap", link: "ضایعات" },
      { title: "انبار خاورشهر", text: "مسیر دسترسی به معرفی انبار و اطلاعات مرتبط با آن.", path: "/khavarshahr", link: "معرفی انبار" },
    ],
    toolsLabel: "دسترسی سریع", toolsTitle: "یک مسیر روشن برای نیاز شما",
    tools: [
      { title: "موجودی روز", text: "مسیر مشاهده‌ی موجودی محصولات", path: "/inventory" },
      { title: "قیمت روز", text: "مسیر مشاهده‌ی قیمت محصولات", path: "/prices" },
      { title: "خرید ضایعات", text: "معرفی ضایعات قابل عرضه‌ی شما", path: "/sell-scrap" },
      { title: "استعلام قیمت", text: "طرح نیاز و درخواست قیمت", path: "/inquiry" },
    ],
    aboutLabel: "درباره‌ی هلدینگ", aboutTitle: "در امتداد زنجیره‌ی تأمین فولاد",
    aboutText: "فعالیت هلدینگ فولاد کاویان سپنتا بر تأمین و تجارت فولاد، آهن‌آلات و ضایعات صنعتی متمرکز است. برای آشنایی بیشتر با مجموعه یا گفت‌وگو درباره‌ی نیازهای خود، از مسیرهای زیر استفاده کنید.",
    aboutLink: "درباره ما", clientsLink: "مشتریان و پروژه‌ها",
    ctaLabel: "شروع گفت‌وگو", ctaTitle: "نیاز پروژه‌ی بعدی شما چیست؟",
    ctaText: "نوع محصول یا ضایعات مورد نظر خود را مشخص کنید و مسیر استعلام قیمت را دنبال کنید.", contactLink: "تماس با ما", visualCaption: "فولاد · تأمین · تجارت",
  },
  en: {
    title: "Understand the market. Manage your business.", eyebrow: "Kavian Market | Steel & scrap",
    description: "Kavian Market: steel and scrap opportunities, rates and market analysis, alongside ERP tailored to business workflows.",
    heroText: "Explore market opportunities, rates and outlook, and discover ERP designed around your business workflows.",
    marketLink: "Explore Kavian Market", erpLink: "Explore ERP", quote: "Request a quote", productsLink: "Explore products", explore: "Explore our areas of activity",
    sectorLabel: "Our focus", sectorTitle: "From steel products to the recycling cycle",
    sectorText: "Explore the holding’s principal areas of activity and find the route that fits your needs.",
    sectors: [
      { title: "Steel products", text: "Steel and metal products for industrial, construction and project requirements.", path: "/products", link: "Products" },
      { title: "Industrial scrap", text: "Explore metal scrap and buying and selling within the industrial supply cycle.", path: "/scrap", link: "Scrap" },
      { title: "Khavarshahr warehouse", text: "Find the warehouse introduction and related information.", path: "/khavarshahr", link: "Warehouse overview" },
    ],
    toolsLabel: "Quick access", toolsTitle: "A clear route to what you need",
    tools: [
      { title: "Daily inventory", text: "Explore product availability", path: "/inventory" },
      { title: "Daily prices", text: "Explore product pricing", path: "/prices" },
      { title: "Sell scrap", text: "Introduce the scrap you wish to sell", path: "/sell-scrap" },
      { title: "Request a quote", text: "Outline your needs and request pricing", path: "/inquiry" },
    ],
    aboutLabel: "About the holding", aboutTitle: "Across the steel supply chain",
    aboutText: "Kavian Sepanta Steel Holding focuses on the supply and trading of steel, metal products and industrial scrap. Learn more about the holding or connect with us to discuss your requirements.",
    aboutLink: "About us", clientsLink: "Clients & projects",
    ctaLabel: "Start a conversation", ctaTitle: "What does your next project need?",
    ctaText: "Identify the steel product or scrap you need and follow the quote request route.", contactLink: "Contact us", visualCaption: "STEEL · SUPPLY · TRADE",
  },
};
