export const warehouseContent = {
  fa: {
    brand: "هلدینگ فولاد کاویان سپنتا", home: "خانه", title: "انبار خاورشهر",
    description: "معرفی انبار مرکزی فولاد کاویان سپنتا در خاورشهر، نشانی و راهنمای هماهنگی پیش از مراجعه.",
    eyebrow: "معرفی انبار", intro: "انبار مرکزی فولاد کاویان سپنتا در محدودهٔ خاورشهر قرار دارد. نشانی و مسیر جست‌وجوی آن در نقشه در ادامه آمده است؛ پیش از مراجعه با دفتر مرکزی هماهنگ کنید.",
    infoTitle: "اطلاعات انبار", pending: "به‌زودی اعلام می‌شود",
    equipmentTitle: "تجهیزات معرفی‌شدهٔ مجموعه",
    equipmentIntro: "کاتالوگ قدیمی، تجهیزات زیر را برای مجموع انبارها و کارخانه‌ها معرفی می‌کند. محل استقرار و وضعیت فعلی هر تجهیز در به‌روزرسانی بعدی مشخص می‌شود.",
    equipment: [
      { count: "۷ دستگاه", title: "برش و پرس آهن‌آلات", text: "برای آماده‌سازی آهن‌آلات و ضایعات آهنی در ابعاد مورد نیاز." },
      { count: "۳ دستگاه", title: "گیوتین تمام‌اتوماتیک", text: "برای برش و قطعه‌کردن آهن‌آلات و ضایعات آهنی." },
      { count: "۵ دستگاه", title: "چنگ هیدرولیکی", text: "برای جابه‌جایی و سامان‌دهی محموله‌ها در محوطه‌های عملیاتی." },
      { count: "۱۳ تن", title: "کورهٔ القایی سپاهان ذوب", text: "ظرفیت ذوب درج‌شده در کاتالوگ برای فعالیت تولیدی مجموعه." },
      { count: "خط CCM", title: "ریخته‌گری پیوسته", text: "خط معرفی‌شده برای تولید شمش فولادی با تجهیزات ساخت ایران." },
      { count: "۲ خاور و ۲ وانت", title: "ناوگان حمل بار", text: "خودروهای حمل بار ذکرشده در فهرست تجهیزات مجموعه." },
    ],
    details: ["آدرس و مسیر دسترسی", "ساعات مراجعه", "راه ارتباطی و هماهنگی", "ظرفیت و مشخصات انبار", "خدمات و امکانات"],
    locationTitle: "موقعیت و دسترسی", locationText: "آدرس دقیق و موقعیت روی نقشه پس از تأیید منتشر می‌شود.",
    imagesTitle: "تصاویر انبار", imagesText: "تصاویر واقعی و تأییدشده‌ی انبار به این بخش اضافه خواهند شد.", imagePlaceholder: "تصویر انبار — در انتظار تکمیل",
    visitTitle: "پیش از مراجعه هماهنگ کنید", visitText: "برای اطلاع از شرایط مراجعه و دسترسی، راه‌های ارتباطی مجموعه را در صفحه‌ی تماس دنبال کنید. شماره‌های دفتر مرکزی و مدیرعامل و مؤسس در صفحهٔ تماس درج شده‌اند.", contact: "تماس با ما", products: "معرفی محصولات",
  },
  en: {
    brand: "Kavian Sepanta Steel Holding", home: "Home", title: "Khavarshahr warehouse",
    description: "The Kavian Sepanta central warehouse in Khavarshahr: address and guidance on arranging your visit.",
    eyebrow: "Warehouse overview", intro: "Kavian Sepanta’s central warehouse is in the Khavarshahr area. Find its address and a map search link below, and coordinate with the head office before visiting.",
    infoTitle: "Warehouse information", pending: "To be announced",
    equipmentTitle: "Equipment described in the catalogue",
    equipmentIntro: "The older catalogue lists this equipment across the group’s warehouses and factories. Its current condition and allocation to individual sites will be updated.",
    equipment: [
      { count: "7 units", title: "Steel cutting & pressing", text: "Preparing steel products and ferrous scrap in the required dimensions." },
      { count: "3 units", title: "Automatic guillotine shears", text: "Cutting steel products and ferrous scrap into smaller sections." },
      { count: "5 units", title: "Hydraulic material handlers", text: "Moving and organizing loads within operational yards." },
      { count: "13 tonnes", title: "Sepahan Zob induction furnace", text: "The melting capacity recorded in the catalogue for the group’s production activities." },
      { count: "CCM line", title: "Continuous casting", text: "A steel billet casting line described as using Iranian-made equipment." },
      { count: "2 trucks & 2 pickups", title: "Load transport", text: "Transport vehicles recorded in the group’s equipment list." },
    ],
    details: ["Address & directions", "Visiting hours", "Contact & coordination", "Capacity & specifications", "Services & facilities"],
    locationTitle: "Location & access", locationText: "The exact address and map location will be published once confirmed.",
    imagesTitle: "Warehouse photographs", imagesText: "Actual, approved photographs of the warehouse will be added here.", imagePlaceholder: "Warehouse photograph — pending",
    visitTitle: "Coordinate before visiting", visitText: "Follow the holding’s contact channels on the contact page for visiting and access information. Head office and CEO and founder phone numbers are listed on the contact page.", contact: "Contact us", products: "Explore products",
  },
};
