export const listingContent = {
  fa: {
    brand: "هلدینگ فولاد کاویان سپنتا", eyebrow: "اطلاعات عرضه و بازار", inventory: "موجودی روز", prices: "قیمت روز",
    inventoryIntro: "مشخصات، مقدار و محل عرضه را بررسی کنید و پیش از تصمیم خرید، وضعیت کالا و شرایط تحویل را استعلام بگیرید.",
    pricesIntro: "هر نرخ را همراه با واحد، نوع قیمت، مالیات، منبع و زمان ثبت بررسی کنید. نرخ ثبت‌شده به‌تنهایی پیشنهاد قطعی معامله نیست.",
    inventoryDescription: "فهرست موجودی محصولات و ضایعات با مشخصات، مقدار، محل عرضه و اطلاعات لازم برای استعلام.",
    pricesDescription: "فهرست نرخ محصولات و ضایعات با تفکیک نوع قیمت، واحد، مالیات، منبع و زمان ثبت.",
    search: "جست‌وجوی کالا، مشخصات یا محل", searchPlaceholder: "نام کالا، سایز یا شهر…", group: "گروه کالا", all: "همهٔ گروه‌ها",
    groups: { flat: "ورق و محصولات تخت", long: "مقاطع و محصولات طویل", hollow: "لوله و مقاطع توخالی", scrap: "ضایعات" },
    priceType: "نوع قیمت", allTypes: "همهٔ انواع", priceTypes: { asking: "پیشنهادی", traded: "معامله‌شده", estimated: "برآوردی" },
    results: "تعداد نتیجه", clear: "پاک‌کردن فیلترها", product: "کالا و مشخصات", location: "محل عرضه", quantity: "مقدار", price: "نرخ و واحد",
    buy: "نرخ خرید", sell: "نرخ فروش", date: "تاریخ اعلام",
    source: "منبع", updated: "زمان ثبت (تهران)", terms: "شرایط معامله", available: "موجود؛ نیازمند تأیید نهایی", confirm: "نیازمند استعلام موجودی",
    tax: { included: "با مالیات", excluded: "بدون مالیات", unspecified: "وضعیت مالیات اعلام نشده" }, currencies: { IRR: "ریال", toman: "تومان" },
    emptyTitle: "هنوز اطلاعات تأییدشده‌ای منتشر نشده است", emptyInventory: "برای بررسی امکان تأمین، مشخصات کالا و مقدار مورد نیاز را آماده و با دفتر مرکزی تماس بگیرید.",
    emptyPrices: "برای دریافت پیشنهاد متناسب با نیازتان، نوع کالا، مقدار و محل تحویل را در متن استعلام مشخص کنید.",
    noResults: "موردی مطابق جست‌وجوی شما پیدا نشد", noResultsHelp: "عبارت دیگری امتحان کنید یا فیلترها را پاک کنید.",
    inquiry: "آماده‌سازی استعلام", contact: "تماس با دفتر مرکزی", relatedInventory: "بررسی موجودی", relatedPrices: "بررسی قیمت‌ها", market: "بازار و فرصت‌ها",
    note: "اطلاعات هر ردیف مربوط به زمان ثبت آن است. موجودی، قیمت و شرایط معامله باید پیش از سفارش دوباره تأیید شوند.",
  },
  en: {
    brand: "Kavian Sepanta Steel Holding", eyebrow: "Supply and market information", inventory: "Daily inventory", prices: "Daily prices",
    inventoryIntro: "Review specifications, quantities and supply locations, then confirm availability and delivery terms before making a purchasing decision.",
    pricesIntro: "Read each rate with its unit, price type, tax status, source and recording time. A listed rate alone is not a binding offer.",
    inventoryDescription: "Product and scrap inventory with specifications, quantities, supply locations and inquiry information.",
    pricesDescription: "Product and scrap rates with price types, units, taxes, sources and recording times.",
    search: "Search products, specifications or locations", searchPlaceholder: "Product name, size or city…", group: "Product group", all: "All groups",
    groups: { flat: "Flat steel products", long: "Sections and long products", hollow: "Pipes and hollow sections", scrap: "Scrap" },
    priceType: "Price type", allTypes: "All types", priceTypes: { asking: "Asking", traded: "Traded", estimated: "Estimated" },
    results: "Results", clear: "Clear filters", product: "Product and specifications", location: "Supply location", quantity: "Quantity", price: "Rate and unit",
    buy: "Purchase rate", sell: "Selling rate", date: "Announcement date",
    source: "Source", updated: "Recorded time (Tehran)", terms: "Commercial terms", available: "Available; final confirmation required", confirm: "Confirm availability",
    tax: { included: "Tax included", excluded: "Tax excluded", unspecified: "Tax status not specified" }, currencies: { IRR: "IRR", toman: "toman" },
    emptyTitle: "No verified information has been published yet", emptyInventory: "Prepare product specifications and required quantities, then contact the head office to discuss supply options.",
    emptyPrices: "Specify the product, quantity and delivery location in your inquiry to request a proposal suited to your needs.",
    noResults: "No matching results", noResultsHelp: "Try another search term or clear the filters.",
    inquiry: "Prepare an inquiry", contact: "Contact the head office", relatedInventory: "View inventory", relatedPrices: "View prices", market: "Market and opportunities",
    note: "Each record describes information at its recording time. Confirm availability, prices and commercial terms again before ordering.",
  },
};
